name: 错误报告
description: 创建一个报告以帮助我们改进
title: '[错误]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告！

  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前检查
      description: |
        在提交 Issue 前请确保您已经完成了以下所有步骤
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非评论区，将尽可能提供更多信息帮助问题解决。
          required: true
        - label: 我已经查看了常见问题并搜索了现有的 [Issue](https://github.com/Zirconium233/yunForNewVersion/issues)，没有找到类似的问题。
          required: true
        - label: 我填写了简短且清晰明确的标题，以便能快速确定大致问题。而不是“求助”、“运行不了”、“怎么配置”等。
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: 校区
      description: 您是哪个校区的？
      options:
        - 翡翠湖
        - 屯溪路
        - 宣区
        - 外校
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 错误描述
      description: 描述问题时请尽可能详细
      placeholder: 告诉我发生了什么...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 重现步骤
      description: 提供详细的重现步骤，以便于我们可以准确地重现问题
      placeholder: |
        1. python main.py
        2. 选择位置，偏移...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 报错信息
      description: 请复制并粘贴任何相关的报错信息和环境信息
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 比如你自己的想法