name: 功能建议
description: 为项目提出新的想法
title: '[功能]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此报告！

  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前检查
      description: |
        在提交 Issue 前请确保您已经完成了以下所有步骤
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非评论区，将尽可能提供更多信息帮助问题解决。
          required: true
        - label: 我已经查看了常见问题并搜索了现有的 [Issue](https://github.com/Zirconium233/yunForNewVersion/issues)，没有找到类似的问题。
          required: true
        - label: 我填写了简短且清晰明确的标题，以便能快速确定大致问题。而不是“求助”、“运行不了”、“怎么配置”等。
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: 校区
      description: 您是哪个校区的？
      options:
        - 翡翠湖
        - 屯溪路
        - 宣区
        - 外校
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 描述你想要的功能
      description: 描述你想要的功能