name: 问一些问题
description: 寻求帮助、讨论问题、提出疑问等...
title: '[讨论]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        感谢你的提问！

  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前检查
      description: |
        在提交 Issue 前请确保您已经完成了以下所有步骤
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非评论区，将尽可能提供更多信息帮助问题解决。
          required: true
        - label: 我已经查看了常见问题并搜索了现有的 [Issue](https://github.com/Zirconium233/yunForNewVersion/issues)，没有找到类似的问题。
          required: true
        - label: 我填写了简短且清晰明确的标题，以便能快速确定大致问题。而不是“求助”、“运行不了”、“怎么配置”等。
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: 校区
      description: 您是哪个校区的？
      options:
        - 翡翠湖
        - 屯溪路
        - 宣区
        - 外校
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 请详细描述您的问题
      description: 请尽可能清楚地说明您的问题...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 你着急吗？
      options:
        - 低 (有空再看)
        - 中 (希望尽快得到答复)
        - 高 (要挂科了，快来救我)
    validations:
      required: true